<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Sign In</name>
   <tag></tag>
   <elementGuidId>a9d9a9a4-f931-477a-8baa-faa0ee734eab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.gun-ui-btn.gun-ui-btn-extra-large.gun-ui-btn-rounded.gun-ui-btn-extra-large-rounded.gun-ui-btn-filled.gun-ui-btn-filled-primary.submit-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='submit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>46277f79-6959-4e35-bca7-ca0e66b36d6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>variant</name>
      <type>Main</type>
      <value>filled</value>
      <webElementGuid>3300a610-899b-4750-9511-6f445d84cf24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>btntype</name>
      <type>Main</type>
      <value>primary</value>
      <webElementGuid>c9513207-2aa3-42b1-995d-a5daf88f87d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>extra-large</value>
      <webElementGuid>39701934-42ef-4e00-b7fc-b19e030eef3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>4ce84869-4af9-4ab5-834a-3283549c75b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gun-ui-btn   gun-ui-btn-extra-large gun-ui-btn-rounded gun-ui-btn-extra-large-rounded gun-ui-btn-filled gun-ui-btn-filled-primary submit-btn </value>
      <webElementGuid>22d7cb83-d8e5-4e7f-a030-5991b863a0f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Sign In </value>
      <webElementGuid>3e64e97a-28c7-4263-a62d-39be1ae29a63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/app-sign-in[1]/div[@class=&quot;sign-in-page&quot;]/div[@class=&quot;form-panel&quot;]/div[@class=&quot;form-panel-inner&quot;]/form[@class=&quot;sign-in-form ng-untouched ng-pristine ng-invalid&quot;]/div[@class=&quot;anim&quot;]/button[@class=&quot;gun-ui-btn   gun-ui-btn-extra-large gun-ui-btn-rounded gun-ui-btn-extra-large-rounded gun-ui-btn-filled gun-ui-btn-filled-primary submit-btn&quot;]</value>
      <webElementGuid>12f91617-13aa-4b59-a623-3b030b251c65</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='submit']</value>
      <webElementGuid>8053ff40-b953-45c5-a011-342e1f3dc4d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Forgot password?'])[1]/following::button[1]</value>
      <webElementGuid>e8710c53-91d5-4329-93d6-cd7cf493b0c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remember me'])[1]/following::button[1]</value>
      <webElementGuid>56342823-acbd-4bdf-8b51-2df3a02e66a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='🔐'])[1]/preceding::button[1]</value>
      <webElementGuid>e581e07b-5586-4ba0-ab73-ea877fc0cd60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Security Information'])[1]/preceding::button[1]</value>
      <webElementGuid>f96485ce-1625-47dc-b440-862405d9ac48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Sign In']/parent::*</value>
      <webElementGuid>0872dfa5-bb1b-4c1e-83c9-9d056eb8dd0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/button</value>
      <webElementGuid>1b410352-e1d3-46f9-bd33-f4f384e7baed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = ' Sign In ' or . = ' Sign In ')]</value>
      <webElementGuid>6a4bfa93-c08f-4e96-a813-127514d040d0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
