<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Remember me</name>
   <tag></tag>
   <elementGuidId>ba74d5b9-6eac-4cd4-b58a-e7ffc3f4ef39</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//gun-checkbox[@formcontrolname='remember']//label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>label.gun-checkbox.border-rad-6.d-flex.align-items-center.gap-4.cursor-pointer.m-0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>94951b06-7de3-40e8-bde8-5aca02ab54f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>e2eid</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>7e2d04f5-4c19-419a-a892-016626ba1692</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gun-checkbox border-rad-6 d-flex align-items-center gap-4 cursor-pointer m-0</value>
      <webElementGuid>b3e1ae36-b823-45d2-990a-603022697089</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>cb-d6d2c96c-98b5-49ec-a6d6-940c9b222196</value>
      <webElementGuid>41a490d1-98be-4cb7-802d-c68383c6055d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-e2e</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>0bb954e2-7328-47bc-8913-07f1041f0856</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Remember me</value>
      <webElementGuid>09250158-988e-4d0c-83cd-c1d28e3893fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/app-sign-in[1]/div[@class=&quot;sign-in-page&quot;]/div[@class=&quot;form-panel&quot;]/div[@class=&quot;form-panel-inner&quot;]/form[@class=&quot;sign-in-form ng-untouched ng-pristine ng-invalid&quot;]/div[@class=&quot;form-options anim&quot;]/gun-checkbox[@class=&quot;gun-checkbox-square ng-untouched ng-pristine ng-valid&quot;]/label[@class=&quot;gun-checkbox border-rad-6 d-flex align-items-center gap-4 cursor-pointer m-0&quot;]</value>
      <webElementGuid>65d733e4-fc91-4d83-a245-06e00577bc0f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password'])[1]/following::label[1]</value>
      <webElementGuid>65d609be-1c75-46be-bdb9-9ed184842261</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email'])[1]/following::label[2]</value>
      <webElementGuid>2c0bfe09-bd5c-403f-8254-61be7c72db95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Forgot password?'])[1]/preceding::label[1]</value>
      <webElementGuid>566fd4a4-98e4-486a-b16a-b01a4e36c0aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//gun-checkbox/label</value>
      <webElementGuid>3fe93223-7b5e-4fa3-a35a-a93ba5a357f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Remember me' or . = 'Remember me')]</value>
      <webElementGuid>d6a94778-35b3-488c-ac01-df1343ab871a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
