<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Remember me</name>
   <tag></tag>
   <elementGuidId>ba74d5b9-6eac-4cd4-b58a-e7ffc3f4ef39</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>label.gun-checkbox.border-rad-6.d-flex.align-items-center.gap-4.cursor-pointer.m-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Password'])[1]/following::label[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>98b38c20-9996-4753-8f19-528d775ee186</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>e2eid</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>3af7906f-5f7f-4bf4-85ec-996508eadbf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gun-checkbox border-rad-6 d-flex align-items-center gap-4 cursor-pointer m-0</value>
      <webElementGuid>14f6ab98-b5ac-4350-9e07-a9f7f3455e22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>cb-d6d2c96c-98b5-49ec-a6d6-940c9b222196</value>
      <webElementGuid>00fb1517-09e9-4579-86f5-5368354941b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-e2e</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>e64aab18-da27-4930-849d-79e2c5595af9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Remember me</value>
      <webElementGuid>a4930f50-a894-4b30-91d0-d3dd19e51584</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/app-sign-in[1]/div[@class=&quot;sign-in-page&quot;]/div[@class=&quot;form-panel&quot;]/div[@class=&quot;form-panel-inner&quot;]/form[@class=&quot;sign-in-form ng-untouched ng-pristine ng-invalid&quot;]/div[@class=&quot;form-options anim&quot;]/gun-checkbox[@class=&quot;gun-checkbox-square ng-untouched ng-pristine ng-valid&quot;]/label[@class=&quot;gun-checkbox border-rad-6 d-flex align-items-center gap-4 cursor-pointer m-0&quot;]</value>
      <webElementGuid>7d4907c7-ffb8-42d6-ac1a-2241b494d08b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password'])[1]/following::label[1]</value>
      <webElementGuid>7f9a7b46-fea2-4e3b-8c50-8a79baffb72a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email'])[1]/following::label[2]</value>
      <webElementGuid>5c74e172-ac2e-4816-b368-0563a4f0d19c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Forgot password?'])[1]/preceding::label[1]</value>
      <webElementGuid>9f7c1289-091f-4437-873d-d399c94b095f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//gun-checkbox/label</value>
      <webElementGuid>f361e926-9223-4291-88b4-962d36dfd212</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Remember me' or . = 'Remember me')]</value>
      <webElementGuid>484001e8-fc28-47aa-8911-e3c3f23e0e0e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
