<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dropdown branch</name>
   <tag></tag>
   <elementGuidId>c5e77bc0-ee61-4a4c-8a59-46e7f513236a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>app-branch-current > div.d-flex.align-items-center.gap-4 > svg.chevron</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[local-name()='svg' and @class='chevron']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>27d8054f-92ff-4670-bffc-3a08d5b9037c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>14</value>
      <webElementGuid>e60d66a0-e9b9-48ca-8111-ab1bdf01015f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>14</value>
      <webElementGuid>a56710c2-6f60-468d-85b0-a68488d7b3e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 24 24</value>
      <webElementGuid>1d7a0067-b4b3-42fb-8d20-0362aa936c9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>6d9f12dc-d2f3-4352-88ed-47544a0b4e1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke</name>
      <type>Main</type>
      <value>currentColor</value>
      <webElementGuid>06576dc2-7318-40b7-8ac9-132878ef7a5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-width</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>5cde36ba-30db-4a34-a857-8a5bd1543414</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-linecap</name>
      <type>Main</type>
      <value>round</value>
      <webElementGuid>1446f538-a9aa-4bd6-9d7a-79c624dd62c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-linejoin</name>
      <type>Main</type>
      <value>round</value>
      <webElementGuid>5eb08579-5aa4-4d7b-9d5b-88d9a0c1c4cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chevron</value>
      <webElementGuid>3ce287cb-1be5-4560-8f51-af9c855bf8ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/app-dashboard[1]/app-header-dashboard[1]/header[@class=&quot;header-container&quot;]/div[@class=&quot;header-left&quot;]/app-branch-switcher[1]/div[@class=&quot;left-header&quot;]/div[@class=&quot;container-header-item&quot;]/app-branch-current[1]/div[@class=&quot;d-flex align-items-center gap-4&quot;]/svg[@class=&quot;chevron&quot;]</value>
      <webElementGuid>507cd4f7-e957-48c1-8241-6887ad9dffdc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='qc test'])[1]/following::*[name()='svg'][1]</value>
      <webElementGuid>00bddb8e-47f0-4d01-93a5-2c58485adfc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bubble Pocker'])[1]/following::*[name()='svg'][3]</value>
      <webElementGuid>67550eb6-69c7-4f39-aa49-87ec9b374725</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EN'])[1]/preceding::*[name()='svg'][3]</value>
      <webElementGuid>0dbd835a-7d55-40d7-9ef5-832b5bffd83a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='JA'])[1]/preceding::*[name()='svg'][3]</value>
      <webElementGuid>19742367-4117-42cd-8564-11d6c7a5a7ea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
