<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dropdown branch</name>
   <tag></tag>
   <elementGuidId>c5e77bc0-ee61-4a4c-8a59-46e7f513236a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//app-branch-current</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>app-branch-current > div.d-flex.align-items-center.gap-4 > svg.chevron</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>cc90266d-4c7e-4994-ad0c-3bfe71463f95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>14</value>
      <webElementGuid>dc58e351-d1a8-4cfe-98b7-1387f03ef308</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>14</value>
      <webElementGuid>f727d656-2b8c-4b68-af54-de4091f9b4af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 24 24</value>
      <webElementGuid>e050b262-1b90-4ebe-8807-f12b68ee22b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>ba8d0249-7b06-4ba0-ae56-fbf6e1f28611</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke</name>
      <type>Main</type>
      <value>currentColor</value>
      <webElementGuid>aeabb28c-31e9-47fd-a96d-e806de001fe4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-width</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>3b7ddc43-c0b5-4167-b7df-d0c3bba74d65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-linecap</name>
      <type>Main</type>
      <value>round</value>
      <webElementGuid>200e08ee-c75a-4a9e-8572-628585a3ac79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-linejoin</name>
      <type>Main</type>
      <value>round</value>
      <webElementGuid>2a38010c-400f-4477-9f41-a421675ed7d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chevron</value>
      <webElementGuid>a420137f-27e9-4248-be8a-096744b05cf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/app-dashboard[1]/app-header-dashboard[1]/header[@class=&quot;header-container&quot;]/div[@class=&quot;header-left&quot;]/app-branch-switcher[1]/div[@class=&quot;left-header&quot;]/div[@class=&quot;container-header-item&quot;]/app-branch-current[1]/div[@class=&quot;d-flex align-items-center gap-4&quot;]/svg[@class=&quot;chevron&quot;]</value>
      <webElementGuid>f3b6b7a6-3b0b-4a4f-b414-77efcc6240ef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='qc test'])[1]/following::*[name()='svg'][1]</value>
      <webElementGuid>681aa3a4-bcfa-4b58-b9c6-fcc2004b43cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bubble Pocker'])[1]/following::*[name()='svg'][3]</value>
      <webElementGuid>6038c5bc-58b6-45b0-b2a9-c13fe104c9d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EN'])[1]/preceding::*[name()='svg'][3]</value>
      <webElementGuid>ebca618e-1f09-4444-be46-56fe8006e21c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='JA'])[1]/preceding::*[name()='svg'][3]</value>
      <webElementGuid>82a07b8f-0d45-47d6-8852-a168724187dd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
