<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Slug</name>
   <tag></tag>
   <elementGuidId>1e367de1-e79a-48ec-9475-dd588fadea9d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#68b8b089-6ae5-4959-8097-4bf13be333a9</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//gun-text-field[@formcontrolname='slug']//input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>13e7ce4d-84dd-45ca-87f5-5b575471bfc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gun-ui-text-field empty not-check-submit ng-untouched ng-pristine ng-valid ng-touched</value>
      <webElementGuid>b0b7a37f-80c3-4119-a31e-4b8bcfc284a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>68b8b089-6ae5-4959-8097-4bf13be333a9</value>
      <webElementGuid>ffe2d23e-1392-4a46-8076-efb8698288ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter tag slug</value>
      <webElementGuid>abd1c5b9-ac40-4130-8b20-c8184e3228e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3985b947-f3ca-4395-81a4-5b07880aaed7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>008bee41-100d-4df1-9ae9-51a4fc9b1648</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-e2e</name>
      <type>Main</type>
      <value>text-input</value>
      <webElementGuid>993e4da4-0582-428a-981b-fed6d9020618</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;68b8b089-6ae5-4959-8097-4bf13be333a9&quot;)</value>
      <webElementGuid>bc78b08d-873a-42a5-8ea5-56342c401583</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='68b8b089-6ae5-4959-8097-4bf13be333a9']</value>
      <webElementGuid>faafc482-fdaa-4cf1-b9b6-b929f163132d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='tagForm']/div/div/div/div/div[2]/gun-form-control[2]/div/gun-text-field/div/input</value>
      <webElementGuid>e5a3a20e-b1b7-4f7e-9e8b-faa12dd4a004</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//gun-form-control[2]/div/gun-text-field/div/input</value>
      <webElementGuid>ea703389-875a-4572-91d6-31707146f691</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = '68b8b089-6ae5-4959-8097-4bf13be333a9' and @placeholder = 'Enter tag slug' and @type = 'text']</value>
      <webElementGuid>36780749-6dd5-4456-bfb3-7b9646cf7db0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
