<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Name</name>
   <tag></tag>
   <elementGuidId>7fe2cb25-50ad-4665-90f5-d793257ffd8c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='6df64c21-76f4-4527-a096-061973b711a5']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#6df64c21-76f4-4527-a096-061973b711a5</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>54cc52bf-6d72-4028-b0bb-f0c41a342fb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gun-ui-text-field empty not-check-submit ng-untouched ng-pristine ng-valid ng-touched</value>
      <webElementGuid>61a455bf-60e1-4780-bc21-2898c6eede82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>6df64c21-76f4-4527-a096-061973b711a5</value>
      <webElementGuid>8aa873ea-cb05-4987-9f41-e98bd56eff1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter tag name</value>
      <webElementGuid>0cef375c-4c08-4269-8777-650619835b70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a16e43e2-e4d6-461f-9284-b569b67bd0f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>abb5b850-4e72-486f-980a-23ad421784d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-e2e</name>
      <type>Main</type>
      <value>text-input</value>
      <webElementGuid>4a984133-c0b9-42ba-a774-bf0227971757</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;6df64c21-76f4-4527-a096-061973b711a5&quot;)</value>
      <webElementGuid>4aeeb413-3ca1-4117-87dc-ea40562e3afe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='6df64c21-76f4-4527-a096-061973b711a5']</value>
      <webElementGuid>9c07f07f-ed10-4d0e-b35d-02731a8dd6a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='tagForm']/div/div/div/div/div[2]/gun-form-control/div/gun-text-field/div/input</value>
      <webElementGuid>29a14bd7-6390-4e36-901a-713a91340b0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>a3e4f93d-3549-4246-92d4-0a23e0c21afa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = '6df64c21-76f4-4527-a096-061973b711a5' and @placeholder = 'Enter tag name' and @type = 'text']</value>
      <webElementGuid>bcf8328e-5e98-402f-8fab-84ad43b37944</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
