<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Slug</name>
   <tag></tag>
   <elementGuidId>1e367de1-e79a-48ec-9475-dd588fadea9d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='68b8b089-6ae5-4959-8097-4bf13be333a9']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#68b8b089-6ae5-4959-8097-4bf13be333a9</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b2ef5481-9dce-4c31-a3c3-c22630db202b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gun-ui-text-field empty not-check-submit ng-untouched ng-pristine ng-valid ng-touched</value>
      <webElementGuid>12b96c54-adb2-40e3-8900-844ea32ba3b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>68b8b089-6ae5-4959-8097-4bf13be333a9</value>
      <webElementGuid>2d4b19cd-8cd5-4d51-9178-2d745674c8e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter tag slug</value>
      <webElementGuid>03b92d4d-6c50-45ae-85b1-9690733f1b15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>132f68c2-1e52-417a-b984-493d96beb98e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>017f2436-0c21-472e-afa6-53e35e6e2ece</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-e2e</name>
      <type>Main</type>
      <value>text-input</value>
      <webElementGuid>7c8aeba0-6fe7-4884-a82d-6d19ab07dfab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;68b8b089-6ae5-4959-8097-4bf13be333a9&quot;)</value>
      <webElementGuid>8f798700-ab1b-4e31-b0db-8650063cfe6a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='68b8b089-6ae5-4959-8097-4bf13be333a9']</value>
      <webElementGuid>2099933c-f87d-41dd-be4c-16af22ff71c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='tagForm']/div/div/div/div/div[2]/gun-form-control[2]/div/gun-text-field/div/input</value>
      <webElementGuid>1ce315c6-7285-4684-b6a1-2561cd2abe21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//gun-form-control[2]/div/gun-text-field/div/input</value>
      <webElementGuid>a2397b76-8255-457a-9d0e-6d5d00c23dc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = '68b8b089-6ae5-4959-8097-4bf13be333a9' and @placeholder = 'Enter tag slug' and @type = 'text']</value>
      <webElementGuid>bb204bb5-0e04-4bc3-bf0e-0dc0c12a6f33</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
