<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_color</name>
   <tag></tag>
   <elementGuidId>3ee5730b-1bf7-4b36-b8a6-90a4e488ef2c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='412458c2-6b78-48f9-8061-28a3e9fd2b4b']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#412458c2-6b78-48f9-8061-28a3e9fd2b4b</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ec8e3f6b-df0e-441c-bc4a-36ef1775e12f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gun-ui-text-field empty not-check-submit ng-untouched ng-pristine ng-valid ng-touched</value>
      <webElementGuid>cd3ea19d-0eb4-4ede-a96c-0f7380a3847e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>412458c2-6b78-48f9-8061-28a3e9fd2b4b</value>
      <webElementGuid>9ab7b75f-cdc9-4347-996b-a6f82fdfd4e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter color (e.g. #FF0000)</value>
      <webElementGuid>48a2fde1-889d-4cef-bffd-fb64c7f671e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e3f9db3f-5e3b-4f5a-90c3-dc0c7f5f8cb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>063808d1-d6bd-4525-8fe1-e03cc962ee4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-e2e</name>
      <type>Main</type>
      <value>text-input</value>
      <webElementGuid>481ddacc-86f9-4ef2-90f0-38861147fabf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;412458c2-6b78-48f9-8061-28a3e9fd2b4b&quot;)</value>
      <webElementGuid>dce94c09-ad65-40f4-85c2-5e4d56c770db</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='412458c2-6b78-48f9-8061-28a3e9fd2b4b']</value>
      <webElementGuid>475d69aa-56b4-487a-a47c-0e05a8d06736</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='tagForm']/div/div/div/div[2]/div[2]/div/gun-form-control/div/div[2]/gun-text-field/div/input</value>
      <webElementGuid>23509533-876d-46ff-a77f-29ba22c25d12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/gun-text-field/div/input</value>
      <webElementGuid>0e88f824-b9c4-45de-a8f3-481b742ef104</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = '412458c2-6b78-48f9-8061-28a3e9fd2b4b' and @placeholder = 'Enter color (e.g. #FF0000)' and @type = 'text']</value>
      <webElementGuid>31e41a06-c72f-42e3-b7bd-9ae135bcb53f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
