<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Lable color</name>
   <tag></tag>
   <elementGuidId>86d98a0f-fae5-4f6d-a3d5-2d1437586b78</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='1310e1ff-228a-42aa-986f-830b664deb7a']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#1310e1ff-228a-42aa-986f-830b664deb7a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f229c74c-9a17-4dde-9bb0-267ec4dfbc86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gun-ui-text-field empty not-check-submit ng-untouched ng-pristine ng-valid ng-touched</value>
      <webElementGuid>47e07603-0ac6-4378-9eb3-8541c3371dfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>1310e1ff-228a-42aa-986f-830b664deb7a</value>
      <webElementGuid>06dd4b45-663a-464e-babf-8c46c040de75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>#000000</value>
      <webElementGuid>b7917090-46f2-44df-aab2-346f6dc05ddb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a1586291-3b0d-4050-828a-f084c57e2694</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>3e23ede9-02f5-4c91-8715-fb2bab655c26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-e2e</name>
      <type>Main</type>
      <value>text-input</value>
      <webElementGuid>afbac4c0-c839-46ef-a600-0b833e3e1f14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;1310e1ff-228a-42aa-986f-830b664deb7a&quot;)</value>
      <webElementGuid>7e37918b-1402-44b1-b854-40889097ea2f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='1310e1ff-228a-42aa-986f-830b664deb7a']</value>
      <webElementGuid>eb3ae9a0-fe10-4fb0-a924-43e2dde090ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='tagForm']/div/div/div/div[2]/div[2]/div/gun-form-control[2]/div/div[2]/gun-text-field/div/input</value>
      <webElementGuid>2f7d39ab-d357-4196-a6e3-df5a7e9d501a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//gun-form-control[2]/div/div[2]/gun-text-field/div/input</value>
      <webElementGuid>5a0f23b3-f7c4-4365-af52-47df2c22471b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = '1310e1ff-228a-42aa-986f-830b664deb7a' and @placeholder = '#000000' and @type = 'text']</value>
      <webElementGuid>ec87920a-7155-4acb-8fc1-da69e23b62ae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
