<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Name</name>
   <tag></tag>
   <elementGuidId>7fe2cb25-50ad-4665-90f5-d793257ffd8c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#6df64c21-76f4-4527-a096-061973b711a5</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//gun-text-field[@formcontrolname='name']//input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c75d019d-8213-4c22-92c7-f224f62079ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gun-ui-text-field empty not-check-submit ng-untouched ng-pristine ng-valid ng-touched</value>
      <webElementGuid>80d5521b-0bcb-44dc-9eb0-8278bbc58ecf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>6df64c21-76f4-4527-a096-061973b711a5</value>
      <webElementGuid>07a0e286-1e57-455d-b89e-8133838e9ceb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter tag name</value>
      <webElementGuid>8ea0a594-5863-48a2-beb6-51ebca36eca2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a5f2dd5f-de3f-499c-9c57-ec5200556143</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>ddaa2e6d-46c6-421a-b99b-4c4158b6bdf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-e2e</name>
      <type>Main</type>
      <value>text-input</value>
      <webElementGuid>d5a33471-91f1-4646-be9c-6dae65788805</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;6df64c21-76f4-4527-a096-061973b711a5&quot;)</value>
      <webElementGuid>85915370-62c4-4df5-9cc1-ce5ca4ef8ebe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='6df64c21-76f4-4527-a096-061973b711a5']</value>
      <webElementGuid>19480782-68ec-46dd-953e-776ca873ab3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='tagForm']/div/div/div/div/div[2]/gun-form-control/div/gun-text-field/div/input</value>
      <webElementGuid>72d7b46a-20c8-457f-b265-cc2a7ddab0c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>6d894fe8-f9c1-4f91-b2f3-2aa950e82b95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = '6df64c21-76f4-4527-a096-061973b711a5' and @placeholder = 'Enter tag name' and @type = 'text']</value>
      <webElementGuid>3a7268ac-3f43-4840-9897-506c5d4a4258</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
