<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_color</name>
   <tag></tag>
   <elementGuidId>3ee5730b-1bf7-4b36-b8a6-90a4e488ef2c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#412458c2-6b78-48f9-8061-28a3e9fd2b4b</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//gun-text-field[@formcontrolname='color']//input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f71fe4a1-5435-483a-a398-d337cbbf5b00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gun-ui-text-field empty not-check-submit ng-untouched ng-pristine ng-valid ng-touched</value>
      <webElementGuid>356c8aa8-b7dd-4339-ae78-b2524118c62e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>412458c2-6b78-48f9-8061-28a3e9fd2b4b</value>
      <webElementGuid>22cdd264-8503-45be-8023-00f1f5857553</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter color (e.g. #FF0000)</value>
      <webElementGuid>ab108114-241b-42f8-b43c-3da342b8fd15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>60f7a52d-7bc3-48db-bac6-e6751107c4c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>1af7a680-259d-4fbc-9ea4-afabbc71e0cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-e2e</name>
      <type>Main</type>
      <value>text-input</value>
      <webElementGuid>be434652-2dd8-4d64-8a40-048663c936d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;412458c2-6b78-48f9-8061-28a3e9fd2b4b&quot;)</value>
      <webElementGuid>82e2dda0-8427-44ef-bb29-e1686e462491</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='412458c2-6b78-48f9-8061-28a3e9fd2b4b']</value>
      <webElementGuid>4052e2d5-cdcf-49c9-b034-dd6d7a32d5ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='tagForm']/div/div/div/div[2]/div[2]/div/gun-form-control/div/div[2]/gun-text-field/div/input</value>
      <webElementGuid>9c37e95b-2f9e-42a9-a953-532ddc74b47f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/gun-text-field/div/input</value>
      <webElementGuid>88da0594-92fa-42dc-9390-f79ed3f23de9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = '412458c2-6b78-48f9-8061-28a3e9fd2b4b' and @placeholder = 'Enter color (e.g. #FF0000)' and @type = 'text']</value>
      <webElementGuid>0d6cae9f-9ecb-40ac-96e5-72bae562278f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
