<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Lable color</name>
   <tag></tag>
   <elementGuidId>86d98a0f-fae5-4f6d-a3d5-2d1437586b78</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#1310e1ff-228a-42aa-986f-830b664deb7a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//gun-text-field[@formcontrolname='labelColor']//input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>45207b41-253d-4e26-b3c8-736c446d895b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gun-ui-text-field empty not-check-submit ng-untouched ng-pristine ng-valid ng-touched</value>
      <webElementGuid>e669c3a0-dca0-421f-afc6-ef5192c67926</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>1310e1ff-228a-42aa-986f-830b664deb7a</value>
      <webElementGuid>40492530-e67f-42b3-aa6b-ca2cbb34d01d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>#000000</value>
      <webElementGuid>1eebebf4-e812-4df0-b2e4-0882d909fd7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>eb395a4b-f760-4fb7-8f12-0d4008a4034a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>992bf79a-11ed-49f5-8ac3-a9eaeef60d3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-e2e</name>
      <type>Main</type>
      <value>text-input</value>
      <webElementGuid>48389fab-aaad-412f-b2d5-39f26b279c8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;1310e1ff-228a-42aa-986f-830b664deb7a&quot;)</value>
      <webElementGuid>77fa6ec8-64dc-4365-9e2e-cf1c512aca38</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='1310e1ff-228a-42aa-986f-830b664deb7a']</value>
      <webElementGuid>198953d1-0db2-4b41-9cec-1aef82fdcbef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='tagForm']/div/div/div/div[2]/div[2]/div/gun-form-control[2]/div/div[2]/gun-text-field/div/input</value>
      <webElementGuid>a7984a64-b1f6-4f59-a8f3-e945f0850b08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//gun-form-control[2]/div/div[2]/gun-text-field/div/input</value>
      <webElementGuid>0eafcd30-8db6-48f6-b039-6b285b2bcef5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = '1310e1ff-228a-42aa-986f-830b664deb7a' and @placeholder = '#000000' and @type = 'text']</value>
      <webElementGuid>99b4d201-871c-4f93-8ebe-c5d709281a43</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
