<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Message empty color</name>
   <tag></tag>
   <elementGuidId>daf2f48c-e2be-42e5-8e88-da51962cfff7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.color-picker-container > gun-form-control.required > div.gun-form-control-wrapper > div.error-container.d-flex.align-items-start.gap-4 > div.error-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//gun-form-control[.//*[@formcontrolname='color']]//div[@class='error-text']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>089d93ce-85f1-4e7d-9031-cdd1dea7f90a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>error-text</value>
      <webElementGuid>14c3538b-a225-493a-ac4f-0bb0c2b7bcb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>表示色を入力してください。</value>
      <webElementGuid>8c92bb5b-9a39-4769-8948-a44efebaa11a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tagForm&quot;)/div[@class=&quot;detail-body&quot;]/div[@class=&quot;detail-layout&quot;]/div[@class=&quot;detail-main&quot;]/div[@class=&quot;detail-card&quot;]/div[@class=&quot;card-body&quot;]/div[@class=&quot;color-picker-container&quot;]/gun-form-control[@class=&quot;required&quot;]/div[@class=&quot;gun-form-control-wrapper&quot;]/div[@class=&quot;error-container d-flex align-items-start gap-4&quot;]/div[@class=&quot;error-text&quot;]</value>
      <webElementGuid>d20ca3e9-be37-4ca9-bbfb-7722855b91e3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='tagForm']/div/div/div/div[2]/div[2]/div/gun-form-control/div/div[3]/div</value>
      <webElementGuid>76364f77-0288-4862-a8cc-df50ecc5805a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/following::div[7]</value>
      <webElementGuid>e7c5d949-6d03-41fc-9b87-83978a673436</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/preceding::div[3]</value>
      <webElementGuid>a4ade94e-ef6e-4e97-9194-bba856b3526b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='表示色を入力してください。']/parent::*</value>
      <webElementGuid>1d8fae91-7fe1-4659-be01-510a86cc37ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div</value>
      <webElementGuid>77066918-5609-4aa0-b28f-364c17331785</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '表示色を入力してください。' or . = '表示色を入力してください。')]</value>
      <webElementGuid>e1446d06-1263-4731-8d60-cda418c5fcbe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
