<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Message empty lable color</name>
   <tag></tag>
   <elementGuidId>f91fde6a-244c-47a8-b0a0-a6655edfaaf8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[contains(@class,'color-picker-label') and contains(.,'ラベル色')]/ancestor::gun-form-control//div[@class='error-text']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>7c609cee-3a70-4ce9-916f-b0655e3bad13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>error-text</value>
      <webElementGuid>f0115ee8-804d-4463-b7bc-e88df7bc346d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ラベル色を入力してください。</value>
      <webElementGuid>63b5c6dd-802c-4aaa-9462-3f0913ad805e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tagForm&quot;)/div[@class=&quot;detail-body&quot;]/div[@class=&quot;detail-layout&quot;]/div[@class=&quot;detail-main&quot;]/div[@class=&quot;detail-card&quot;]/div[@class=&quot;card-body&quot;]/div[@class=&quot;color-picker-container&quot;]/gun-form-control[@class=&quot;required&quot;]/div[@class=&quot;gun-form-control-wrapper&quot;]/div[@class=&quot;error-container d-flex align-items-start gap-4&quot;]/div[@class=&quot;error-text&quot;]</value>
      <webElementGuid>8ce1be4c-18c9-409d-a1b6-6d29899077dd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='tagForm']/div/div/div/div[2]/div[2]/div/gun-form-control[2]/div/div[3]/div</value>
      <webElementGuid>33c9156f-7dfc-4e83-9ba5-de36e5c2b682</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/following::div[7]</value>
      <webElementGuid>8f9d4973-e4ba-4ab3-b38a-5b86b9f6ac2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ステータス'])[1]/preceding::div[3]</value>
      <webElementGuid>60fa7ae7-dc6f-4126-9cdd-54e92c36af5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ステータス'])[2]/preceding::div[4]</value>
      <webElementGuid>d424a3e3-d20b-49d1-ba3e-ad41bffd5f23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ラベル色を入力してください。']/parent::*</value>
      <webElementGuid>c6eee3f6-c3ec-4e0d-b1c1-00bf61635764</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//gun-form-control[2]/div/div[3]/div</value>
      <webElementGuid>fbb6bb51-2734-4011-aa20-a68ee3355eba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'ラベル色を入力してください。' or . = 'ラベル色を入力してください。')]</value>
      <webElementGuid>9eb714d2-90c0-4ebf-a6b0-8d2e326d33b6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
