<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Back</name>
   <tag></tag>
   <elementGuidId>94c4ce55-e8c1-482f-8b57-51f3188c6384</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='button']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.gun-ui-btn.gun-ui-btn-large.gun-ui-btn-rounded.gun-ui-btn-large-rounded.gun-ui-btn-filled.gun-ui-btn-filled-primary</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>70041200-6c76-4037-b975-6319f10c3917</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5231b394-020c-4004-a0c8-f8aa62ea0b56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>color</name>
      <type>Main</type>
      <value>secondary</value>
      <webElementGuid>49d55975-7e6e-45cf-9008-99c056c768b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>b223d766-0d51-4869-9b3a-e0c928bc6213</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gun-ui-btn   gun-ui-btn-large gun-ui-btn-rounded gun-ui-btn-large-rounded gun-ui-btn-filled gun-ui-btn-filled-primary  </value>
      <webElementGuid>0a1e657f-de74-4e72-8f9b-31c2135fc585</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Back </value>
      <webElementGuid>668c9c08-7085-4283-af4a-8ca4af8a92fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/app-management[1]/div[@class=&quot;management-container&quot;]/div[@class=&quot;management-content&quot;]/app-article-detail[1]/div[@class=&quot;article-detail-wrapper&quot;]/div[@class=&quot;page-header&quot;]/div[@class=&quot;header-actions&quot;]/button[@class=&quot;gun-ui-btn   gun-ui-btn-large gun-ui-btn-rounded gun-ui-btn-large-rounded gun-ui-btn-filled gun-ui-btn-filled-primary&quot;]</value>
      <webElementGuid>d90301fe-a732-4d9d-8cf5-22f45dd6d581</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='button']</value>
      <webElementGuid>bea4c80f-d72d-450b-9f27-babbfab99a62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Article'])[1]/following::button[1]</value>
      <webElementGuid>279c0830-f2bf-44e1-bc52-c21e76b84165</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Users'])[1]/following::button[2]</value>
      <webElementGuid>d9a302be-43ec-4420-ad22-709d0fc85096</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save Draft'])[1]/preceding::button[1]</value>
      <webElementGuid>a78bec72-1220-4e6b-87bb-b3d54391c0c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save'])[1]/preceding::button[2]</value>
      <webElementGuid>045364ae-2da7-4bde-929a-41525c669f45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Back']/parent::*</value>
      <webElementGuid>f2ec45cd-49e6-4634-bb8f-33cc2cd8a52a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>5f621d4d-7877-4c87-832a-def777790968</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = ' Back ' or . = ' Back ')]</value>
      <webElementGuid>33154085-c7aa-47ea-ab32-f90f9987c388</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
