<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Editor-content</name>
   <tag></tag>
   <elementGuidId>1a911159-3caa-4e08-86af-61cc1c02f0c1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='tiptap-6x2ojjl']/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.editor-content</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>aa9d9d56-5647-422f-83ff-d650b7985b7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>editor-content</value>
      <webElementGuid>dcfba38f-acf4-4722-abda-a30b397e4caa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tiptap-6x2ojjl&quot;)/div[@class=&quot;editor-content&quot;]</value>
      <webElementGuid>35ef051e-a594-48d9-a8d7-f046e96caa2e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tiptap-6x2ojjl']/div[2]</value>
      <webElementGuid>fa68986b-cb36-49d2-a4ea-5196f9ff79d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Paragraph'])[1]/following::div[9]</value>
      <webElementGuid>0cd1f275-e822-4c1b-ad4c-b1942c1426ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/following::div[15]</value>
      <webElementGuid>4d53352a-481c-4247-b5f0-20d5ce85eb31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Content is required'])[1]/preceding::div[2]</value>
      <webElementGuid>6b84a9e5-0fd2-44c7-8d6f-7c99c49d44dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Organization'])[2]/preceding::div[4]</value>
      <webElementGuid>e9ec4c83-4cd8-4d06-84e4-b036f6e4228d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-tiptap-editor/div/div/div[2]</value>
      <webElementGuid>0abc8cee-123b-4827-a9b7-bf2af4281c29</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
