<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Title</name>
   <tag></tag>
   <elementGuidId>2b8102e4-33fe-491d-a881-aa36bb94fae8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='fe303b12-3f5d-4bc3-9f54-f71095b7a144']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#fe303b12-3f5d-4bc3-9f54-f71095b7a144</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>38d7f1be-6d29-4703-8ed6-94d854d9f1d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gun-ui-text-field empty not-check-submit ng-pristine ng-valid ng-touched</value>
      <webElementGuid>4ffa362a-859a-4f06-9d26-6c49643b0ad3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fe303b12-3f5d-4bc3-9f54-f71095b7a144</value>
      <webElementGuid>a6b5a7b0-4eb3-4417-8779-300f359d55e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter article title</value>
      <webElementGuid>33be7e94-bba2-4643-b1d3-5c5d82a8c3d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>213eae2d-a51c-448b-80e5-5d8dfd4878ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>ce32d32d-6311-4d9d-91fc-62e8190c6ca7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-e2e</name>
      <type>Main</type>
      <value>text-input</value>
      <webElementGuid>3d3ddbc6-4d15-489d-a3f2-bcfbe9c3f173</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fe303b12-3f5d-4bc3-9f54-f71095b7a144&quot;)</value>
      <webElementGuid>e80f6a7c-87ba-4f18-ad92-a6c89054c6f2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='fe303b12-3f5d-4bc3-9f54-f71095b7a144']</value>
      <webElementGuid>06fdeba2-7f1f-4839-be4b-1516c0e23276</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='articleForm']/div/div/div/div/div[2]/gun-form-control/div/gun-text-field/div/input</value>
      <webElementGuid>eff1cb7e-5910-4d64-a801-b45a422478b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>2d610f38-7d67-49a2-819c-f178eb162ae7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'fe303b12-3f5d-4bc3-9f54-f71095b7a144' and @placeholder = 'Enter article title' and @type = 'text']</value>
      <webElementGuid>1223f524-a8ca-4c9f-9473-85ff9b677866</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
