<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Slug (1)</name>
   <tag></tag>
   <elementGuidId>f546dbe4-ed68-4b5c-9562-39214e0ed591</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='d75b07eb-d8b5-4487-bb5a-6bd02982113b']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#d75b07eb-d8b5-4487-bb5a-6bd02982113b</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f6019b44-a3f3-4526-9ed6-991d475c6a41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gun-ui-text-field empty not-check-submit ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>7c9f9844-bf0f-4b4f-ae21-99c21ae82e86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>d75b07eb-d8b5-4487-bb5a-6bd02982113b</value>
      <webElementGuid>6252e806-1535-49fd-b49c-426cd571f294</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter article slug</value>
      <webElementGuid>fa254f84-f5ba-4f5d-9ec9-cbfba844951d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7142fd4d-c432-4865-829b-97c3fd5b3ebf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>d2566e9c-3ac5-4bd8-ae8e-9b312fcbbf30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-e2e</name>
      <type>Main</type>
      <value>text-input</value>
      <webElementGuid>55f010e1-2793-4cc1-81ec-54b782c8a8ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;d75b07eb-d8b5-4487-bb5a-6bd02982113b&quot;)</value>
      <webElementGuid>34c945d8-b3c2-47c3-93cb-ea03e05e634e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='d75b07eb-d8b5-4487-bb5a-6bd02982113b']</value>
      <webElementGuid>27885931-5d51-428d-afe0-9976db4c3bc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='articleForm']/div/div/div/div/div[2]/gun-form-control[2]/div/gun-text-field/div/input</value>
      <webElementGuid>cda71570-dc7f-4dd8-9aa6-1391b143cd46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//gun-form-control[2]/div/gun-text-field/div/input</value>
      <webElementGuid>59ffb287-9635-4791-86f8-2dad6583cb44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'd75b07eb-d8b5-4487-bb5a-6bd02982113b' and @placeholder = 'Enter article slug' and @type = 'text']</value>
      <webElementGuid>a1ea5f87-c2be-4494-9e1e-35bdeb17366f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
