<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Event</name>
   <tag></tag>
   <elementGuidId>7820c3e6-0ab3-4cd6-b1ce-6dc73cb85f1b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='articleForm']/div/div/div/div[2]/div[2]/div/gun-form-control/div/app-flat-multi-select/div/div[2]/div[2]/ul/li</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.fms-item</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>e7ab504d-6e10-46d8-8b2e-4a5fa10ed669</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>f9ea1af1-ae1c-479b-9d61-e4d8f98421fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>48bd9064-894b-406c-a901-d22fcc77fce2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fms-item</value>
      <webElementGuid>57ccaf13-0481-464b-a18f-e970ec83048a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>6a605f69-c639-4193-a276-5c88b86eae57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Event</value>
      <webElementGuid>dae82f24-5b46-4c81-8fcd-48f1a51a3ae1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;articleForm&quot;)/div[@class=&quot;detail-body&quot;]/div[@class=&quot;detail-layout&quot;]/div[@class=&quot;detail-main&quot;]/div[@class=&quot;detail-card&quot;]/div[@class=&quot;card-body&quot;]/div[@class=&quot;organization-grid&quot;]/gun-form-control[@class=&quot;required&quot;]/div[@class=&quot;gun-form-control-wrapper&quot;]/app-flat-multi-select[@class=&quot;ng-untouched ng-pristine ng-invalid&quot;]/div[@class=&quot;fms-wrapper&quot;]/div[@class=&quot;fms-panel fms-panel--upward&quot;]/div[@class=&quot;fms-panel__body&quot;]/ul[@class=&quot;fms-item-list&quot;]/li[@class=&quot;fms-item&quot;]</value>
      <webElementGuid>76eac76f-733d-4485-85a0-3b22bf5d5827</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='articleForm']/div/div/div/div[2]/div[2]/div/gun-form-control/div/app-flat-multi-select/div/div[2]/div[2]/ul/li</value>
      <webElementGuid>8a660924-d1bb-4689-b29e-a370067ab0d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select all'])[1]/following::li[1]</value>
      <webElementGuid>5307998f-28d5-41f7-a13e-610ee12142ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select tags'])[1]/following::li[1]</value>
      <webElementGuid>a9c1baea-b572-429d-bcf6-e7170ca89dd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Promotion'])[1]/preceding::li[1]</value>
      <webElementGuid>beaabc38-a782-45ec-aff0-743b04b8fcfb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ul/li</value>
      <webElementGuid>d749a2b0-67c5-4c6a-a504-71c40633215f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'Event' or . = 'Event')]</value>
      <webElementGuid>c8414edd-b53d-463e-99a9-89da92379b3b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
