<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Tournament</name>
   <tag></tag>
   <elementGuidId>a2db3776-1934-46f5-8aa4-bb9ac187dbb6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='articleForm']/div/div/div/div[2]/div[2]/div/gun-form-control/div/app-flat-multi-select/div/div[2]/div[2]/ul/li[4]/span[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>a9cb0e58-6b8a-46b3-a92e-ceb24fe41a41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fms-item__label</value>
      <webElementGuid>32a96d54-5885-4539-b5b9-9d6f80639a11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tournament</value>
      <webElementGuid>701f83d5-a34b-4a57-8677-2add6b9d0c22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;articleForm&quot;)/div[@class=&quot;detail-body&quot;]/div[@class=&quot;detail-layout&quot;]/div[@class=&quot;detail-main&quot;]/div[@class=&quot;detail-card&quot;]/div[@class=&quot;card-body&quot;]/div[@class=&quot;organization-grid&quot;]/gun-form-control[@class=&quot;required&quot;]/div[@class=&quot;gun-form-control-wrapper&quot;]/app-flat-multi-select[@class=&quot;ng-untouched ng-pristine ng-invalid&quot;]/div[@class=&quot;fms-wrapper&quot;]/div[@class=&quot;fms-panel fms-panel--upward&quot;]/div[@class=&quot;fms-panel__body&quot;]/ul[@class=&quot;fms-item-list&quot;]/li[@class=&quot;fms-item&quot;]/span[@class=&quot;fms-item__label&quot;]</value>
      <webElementGuid>c56126d0-2d95-4566-9e84-b73199d04b57</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='articleForm']/div/div/div/div[2]/div[2]/div/gun-form-control/div/app-flat-multi-select/div/div[2]/div[2]/ul/li[4]/span[2]</value>
      <webElementGuid>10c922d3-76bf-4d66-95f4-63add06c70fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Announcement'])[1]/following::span[2]</value>
      <webElementGuid>e2ee7099-84a1-4d02-a597-f44d1d3ea9ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Promotion'])[1]/following::span[4]</value>
      <webElementGuid>e191acaa-91be-44a8-bb68-944e82efa4be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Update'])[1]/preceding::span[2]</value>
      <webElementGuid>029da0ea-414f-480f-9033-ef1b9d7fa585</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Branches'])[2]/preceding::span[3]</value>
      <webElementGuid>d731d635-f068-4393-bde9-b545362fafaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Tournament']/parent::*</value>
      <webElementGuid>0cef77dd-c70e-419b-9e12-7e07072cee06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/span[2]</value>
      <webElementGuid>a798f6c3-632d-48ef-be17-106251e042cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Tournament' or . = 'Tournament')]</value>
      <webElementGuid>e2fe20bb-610c-4c94-bb22-b72c76196b12</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
