<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Push message</name>
   <tag></tag>
   <elementGuidId>bc04eb28-b184-4758-989a-5c7208c147d4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='gun-textarea']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#gun-textarea</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>c2ddb359-d0e3-47d4-93cf-726b241417b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gun-textarea</value>
      <webElementGuid>bf47d3a3-0689-43f6-b400-bd530de92c59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c922d213-83a6-4630-957d-7b9dd9e4484e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gun-ui-textarea empty not-check-submit ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>a8eb333c-d4c0-49b2-aaec-2a5dc72b1d87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter push notification message</value>
      <webElementGuid>26cf68b7-2fa1-4a52-9ad4-9248a29b3b79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>10c16ddc-dcf6-4484-b4fb-6163a72c0ccc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gun-textarea&quot;)</value>
      <webElementGuid>a8a73c21-d38f-41f5-894f-8b702780a279</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='gun-textarea']</value>
      <webElementGuid>f7a5a2cd-5073-4dee-98ce-272e44e08229</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='articleForm']/div/div/div/div[3]/div[2]/gun-form-control[3]/div/gun-textarea/div[2]/textarea</value>
      <webElementGuid>8ff74588-5f48-4c22-bd13-014e82b03ea0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>ab9b612d-d1bf-400e-ad06-49b123a3b365</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'gun-textarea' and @type = 'text' and @placeholder = 'Enter push notification message']</value>
      <webElementGuid>413259b6-3742-4d06-b60f-cc10f32e42ba</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
